class Commands:
    LEECH = "leech@djanilson23_bot"
    PURGE = "purge@djanilson23_bot"
    PAUSEALL = "pauseall@djanilson23_bot"
    RESUMEALL = "resumeall@djanilson23_bot"
    STATUS = "status@djanilson23_bot"
    SETTINGS = "settings@djanilson23_bot"
    EXEC = "exec@djanilson23_bot"
    UPLOAD = "upload@djanilson23_bot"
    YTDL = "ytdl@djanilson23_bot"
    PYTDL = "pytdl@djanilson23_bot"
    ABOUT = "about@djanilson23_bot"
    GETLOGS = "getlogs@djanilson23_bot"
    SERVER = "server@djanilson23_bot"
    USERSETTINGS = "usetting@djanilson23_bot"
    INSTADL = "instadl@djanilson23_bot"
